language: node_js
os:
  - linux
node_js:
  - 10
  - 9
install:
- node -v
- cd gui && npm install
script:
- npm run build
env:
  - YARN_GPG=no
after_success:
  - cd ..
after_script:
- bash ./.teleNotify.sh  
