language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
install:
- npm install -g angular-cli
- (cd gui && npm install)
script:
- (cd gui && ng lint)
- (cd gui && ng test --watch=false)
- (cd gui && ng serve &)

